### ISSUE TITLE
Missing udev rules to allow student access to ST-Link and DFU

### ISSUE THREAD

**Issue by ryankurte** [UoAESRG/cs704#3]
Yesterday we discovered student users do not have the appropriate rights to interact with USB devices on FoE Linux machines (need to test things work /without/ sudo...).

We have provided a set of udev rules to FoE IT to deploy to the linux image, will update this issue once these have been deployed.

**Comment by AndrewChenUoA** [comment]
Good luck with this - apparently it takes a couple of weeks for changes to
the main Linux image to propagate throughout the PCs. May have to use the
beta system in the interim.

**Comment by zacre** [comment]
(Note to self: check `/etc/udev/rules.d` for the appropriate rules files)

**Comment by ryankurte** [comment]
Should be something like:
/etc/udev/rules.d/49-awsam.rules 
/etc/udev/rules.d/49-stlink.rules

**Comment by ryankurte** [comment]
FoE Linux beta image has been updated and is now working.

[Rules](https://github.com/UoAESRG/cs704/files/505332/rules.zip) attached in case they are needed in future.
